"""Scenario planner — compare base / conservative / aggressive / custom futures."""

import json
import argparse
import numpy as np
from src.forecast import forecast_all_channels, HORIZONS


PREDEFINED = {
    'base': {
        'label': 'Base Case',
        'description': 'Current trends continue unchanged',
        'cpc_change': 0.0,
        'cvr_change': 0.0,
        'seasonal_uplift': 0.0,
    },
    'conservative': {
        'label': 'Conservative',
        'description': 'CPC +15%, CVR −10%',
        'cpc_change': 0.15,
        'cvr_change': -0.10,
        'seasonal_uplift': 0.0,
    },
    'aggressive': {
        'label': 'Aggressive',
        'description': 'CPC −5%, CVR +10%, seasonal +15%',
        'cpc_change': -0.05,
        'cvr_change': 0.10,
        'seasonal_uplift': 0.15,
    },
    'custom': {
        'label': 'Custom',
        'description': 'User-defined assumptions',
        'cpc_change': 0.0,
        'cvr_change': 0.0,
        'seasonal_uplift': 0.0,
    },
}


def _adjust(base_p10: float, base_p50: float, base_p90: float,
            cpc: float, cvr: float, seasonal: float) -> dict:
    """Apply scenario assumptions to a point forecast."""
    mult = (1.0 + cvr) * (1.0 + seasonal) / max(1.0 + cpc, 0.01)
    return {
        'revenue_p10': round(max(0, base_p10 * mult), 2),
        'revenue_p50': round(max(0, base_p50 * mult), 2),
        'revenue_p90': round(max(0, base_p90 * mult), 2),
    }


def generate(features_path: str, horizon: int = 30,
             custom: dict = None) -> dict:
    """Compute base forecast then apply scenario assumptions.

    Parameters
    ----------
    features_path : str
        Path to the parquet features file (generated by generate_features).
    horizon : int
        Forecast horizon in days (30/60/90).
    custom : dict or None
        Optional overrides for the 'custom' scenario, e.g.
        ``{'cpc_change': 0.1, 'cvr_change': -0.05, 'seasonal_uplift': 0.02}``.

    Returns
    -------
    dict
        Nested dict: scenario_name -> {channels: {ch: ...}, blended: ...}
    """
    # 1. Get base forecast (independent channels)
    forecast = forecast_all_channels(features_path)

    # Channels to model (skip blended — compute from sum)
    channels = [ch for ch in forecast if ch != 'blended']
    if not channels:
        return {'error': 'No channel forecasts available'}

    # 2. Build each scenario
    scenarios = {}
    for name, defn in PREDEFINED.items():
        if name == 'custom' and custom is not None:
            ass = {'cpc_change': custom.get('cpc_change', 0.0),
                   'cvr_change': custom.get('cvr_change', 0.0),
                   'seasonal_uplift': custom.get('seasonal_uplift', 0.0)}
        else:
            ass = defn

        ch_data = {}
        blended = {'revenue_p10': 0.0, 'revenue_p50': 0.0, 'revenue_p90': 0.0}

        for ch in channels:
            fc = forecast[ch].get(horizon, {})
            bp50 = fc.get('revenue_p50', 0)
            bp10 = fc.get('revenue_p10', 0)
            bp90 = fc.get('revenue_p90', 0)

            adj = _adjust(bp10, bp50, bp90,
                          ass['cpc_change'], ass['cvr_change'], ass['seasonal_uplift'])
            ch_data[ch] = adj
            blended['revenue_p10'] += adj['revenue_p10']
            blended['revenue_p50'] += adj['revenue_p50']
            blended['revenue_p90'] += adj['revenue_p90']

        blended['revenue_p10'] = round(blended['revenue_p10'], 2)
        blended['revenue_p50'] = round(blended['revenue_p50'], 2)
        blended['revenue_p90'] = round(blended['revenue_p90'], 2)

        scenarios[name] = {
            'label': defn['label'],
            'description': defn['description'],
            'channels': ch_data,
            'blended': blended,
        }

    return scenarios


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--features', default='features.parquet')
    parser.add_argument('--horizon', type=int, default=30, choices=[30, 60, 90])
    parser.add_argument('--out', default='./output/scenarios.json')
    parser.add_argument('--custom', default=None,
                        help='JSON string for custom assumptions')
    args = parser.parse_args()

    custom = json.loads(args.custom) if args.custom else None
    result = generate(args.features, args.horizon, custom)
    with open(args.out, 'w') as f:
        json.dump(result, f, indent=2)
    print(f"Scenarios saved to {args.out}")
    for name, sc in result.items():
        bl = sc.get('blended', {})
        print(f"  {sc.get('label', name)}: ${bl.get('revenue_p50', 0):,.0f}  [{sc.get('description', '')}]")
